import java.util.Properties
import sbt._
import Keys._

import sbtassembly.Plugin.AssemblyKeys._
import com.socrata.socratasbt.SocrataSbt._
import SocrataSbtKeys._
import com.rojoma.simplearm.util._

object SocrataEvents extends Build {
  def tagVersion(resourceManaged: File, version: String, scalaVersion: String): Seq[File] = {
    val file = resourceManaged / "build.properties"
    val revision = Process(Seq("git", "describe", "--always", "--dirty")).!!.split("\n")(0)
    val branch = Process(Seq("git", "rev-parse", "--abbrev-ref", "HEAD")).!!.split("\n")(0)
    val lastCommits = Process(Seq("git", "reflog", "-n 10")).!!

    resourceManaged.mkdirs()
    for {
      stream <- managed(new java.io.FileOutputStream(file))
      w <- managed(new java.io.OutputStreamWriter(stream, "UTF-8"))
    } {
      val props = new Properties
      props.setProperty("name", SocrataEvents.getClass.getName)
      props.setProperty("version", version)
      props.setProperty("build_name", branch)
      props.setProperty("build_branch_name", branch)
      props.setProperty("build_revision", revision)
      props.setProperty("build_last_few_commits", lastCommits)
      props.store(w, "Autogenerated by SBT")
    }

    Seq(file)
  }

  lazy val socrataEvents = Project(
    "socrata-events",
    file("."),
    settings = BuildSettings.buildSettings ++ socrataProjectSettings(assembly = true) ++ Seq(Keys.parallelExecution := false) ++ Seq(
    libraryDependencies <++= (slf4jVersion) { slf4jVersion =>
      Seq(
      "com.twitter" %% "twitter-server" % "1.3.1",
      "com.socrata" %% "eurybates" % "0.1.2",
      "com.socrata" %% "socrata-zookeeper" % "0.0.1",
      "org.apache.activemq" % "activemq-core" % "5.3.0",
      "com.socrata" %% "eurybates" % "0.1.1",
      "com.netflix.curator" % "curator-x-discovery" % "1.3.3",
      "com.netflix.curator" % "curator-framework" % "1.3.3",
      "com.netflix.astyanax" % "astyanax" % "1.56.44",
      "org.slf4j" % "slf4j-api" % slf4jVersion,
      "org.slf4j" % "slf4j-log4j12" % slf4jVersion,
      "log4j" % "log4j" % "1.2.16"
    ) },
      discoveredMainClasses in Compile := Seq("com.socrata.eventlog.EventServer"),
      resourceGenerators in Compile <+= (resourceManaged in Compile, version in Compile, scalaVersion in Compile) map tagVersion,
    jarName in assembly <<= name(_ + "-jar-with-dependencies.jar"),
    resolvers += "twitter-maven" at "http://maven.twttr.com"
  )
  )
}
